version: '3.3'

services:
  spot_pose_estimation:
    network_mode: host
    environment:
    - DISPLAY=$DISPLAY
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/tmp/.docker.xauth
    - SSH_AUTH_SOCK=/ssh-agent
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
    - '/tmp/.X11-unix:/tmp/.X11-unix'
    - ${SSH_AUTH_SOCK}:/ssh-agent
    - /dev/shm:/dev/shm
    # - '/:/host:ro'
    # - './inference.py:/OnePose_Plus_Plus_Spot/inference.py'
    - './outputs:/OnePose_Plus_Plus_Spot/outputs'
    devices:
    - /dev/dri
    privileged: true
    runtime: nvidia
    shm_size: '50gb'
    image: registry.ethz.ch/cvg/robotics/spot_pose_estimation:hermann
    command: python3 /OnePose_Plus_Plus_Spot/run.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
  spot_pose_estimation_train:
    network_mode: host
    environment:
    - DISPLAY=$DISPLAY
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/tmp/.docker.xauth
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
    - '/tmp/.X11-unix:/tmp/.X11-unix'
    - '/:/host:ro'
    - './inference.py:/OnePose_Plus_Plus_Spot/inference.py'
    - './outputs:/OnePose_Plus_Plus_Spot/outputs'
    - './ros2/spot_pose_estimation:/ros2_ws/src/spot_pose_estimation'
    - './data:/data'
    - './sfm_model:/OnePose_Plus_Plus_Spot/data'
    devices:
    - /dev/dri
    privileged: true
    runtime: nvidia
    shm_size: '70gb'
    image: registry.ethz.ch/cvg/robotics/spot_pose_estimation:hermann
    command: python3 /OnePose_Plus_Plus_Spot/run.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
